databases:
  - name: render-test
    databaseName: render_test_production
    # user: render-test

services:
  - type: web
    name: render-test
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: render-test
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false